urls.py
from django.conf.urls import url,include

from . import views
from django.views.generic import TemplateView

urlpatterns = [

    # url(r'^publishers/$', views.PublisherList.as_view()),

    # ex: /tst/
    # url(r'^$', views.index, name='index'),

	# ex: /tst/hello    
    url(r'^$', views.index, name='hello'),

    url(r'^test/$', views.test, name='test'),
    url(r'^test/CCXhit$', views.test__CCXhit__S35, name='test'),
    url(r'^test/CCXhit_homsf$', views.test__CCXhit_homsf, name='test'),
    url(r'^test/ConXhit$', views.tab__contrast__crosshit),

    # url(r'^figure(?P<url>.*)$',views.redirect,name='figure_reverse'),### WTF do I need this handler???????

    url(r'^figure/hit4cath2cath$', views.test__scatterplot__hit4cath2cath, name= 'test'),
    url(r'^figure/tst/test/CCXhit', views.test__scatterplot__CCXhit, name= 'test'),
    url(r'^figure/tst/CCXhit', views.test__scatterplot__CCXhit, name= 'test'),
    url(r'^figure/tst/test/CCXhit_homsf$', views.test__scatterplot__CCXhit_homsf, name= 'test'),
    url(r'^figure/tst/test/ConXhit$', views.scatterplot__contrast__crosshit, name= 'test'),

    url(r'^hitlist_compare/$', views.tab__hitlistPR, name='tab__hitlistPR'),
    url(r'^figure/tst/hitlist_compare/$', views.scatterplot__hitlistPR,),
    # url(r'^figure/tst/hitlist_compare$', views.test__scatterplot__hitlistPR, name='test'),

    # url(r'^figure/tst/test/CCXhit_homsf$', views.test__scatterplot_hit4cath2cath, name= 'test'),

    url(r'^CCXhit/$', views.test__CCXhit__S35, name='CCXhit_handler'),
    url(r'^saved/$', TemplateView.as_view(template_name="tst/saved_table.html")),





    # ex:/tst/domain
    url(r'^domain/$',
    	views.domain_collection,
    	name = 'domain_collection'),

    # ex:/tst/domain/d1fpzD00/
    url(r'^domain/(?P<domain_id>[\d,a-z,A-Z]+)/$',
    	views.domain_detail,
    	name = 'domain_detail'),

	# ex:/tst/superfamily/3.90.190.10/    
    url(r'^superfamily/$',
        views.homsf_collection,
        name = 'homsf_collection'),

	url(r'^superfamily/id/(?P<homsf_id>[\d,\.]+)/$',
        views.domain_collection,
        name = 'domain_collection'),

	# url(r'^superfamily/(?P<homsf_id>[\d,\.]+)/$',
	# 	views.homsf_s35_collection,
	# 	name = 'homsf_s35_collection'),


    ## Test figures suite
    url(r'^view3d$', views.view3d, name='hello'),
    url(r'^figure/scplot$', views.scatterplot_homsf, {'homsf_id':'1.10.30.10'},name= 'test'),
    url(r'^figure/scplot_err$', views.scatterplot_homsf, {'homsf_id':'1.10.60.10'},name= 'test'),




    # url(r'^figure/handler/$',views.scatterplot_qset,name='figure_handler'),
    # url(r'^figure/superfamily/(?P<homsf_id>[\d,\.]+)/$', views.scatterplot_homsf,name='fig_nbscatter'),


    # url(r'^superfamily/id/(?P<homsf_id>[\d,\.]+)/figure$', views.scatterplot_homsf,name='fig_nbscatter'),
    # url(r'^superfamily/figure$', views.scatterplot_homsfM,name='fig_nbscatter'),
    url(r'^figure/tst/superfamily/id/(?P<homsf_id>[\d,\.]+)/$', views.scatterplot_domain,name='scatterplot_domain'),
    url(r'^figure/tst/superfamily/$', views.scatterplot_homsf,name='scatterplot_homsf'),
    url(r'^figure/tst/domain/$', views.scatterplot_domain,name='scatterplot_domain_default'),

   

]

models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime
from django.utils import timezone
from django.db import models
from django.db.models import Avg,StdDev,Count, Q , F
# from django.db.models import *
from django.urls import reverse
from django.templatetags.static import static

from django.dispatch import receiver
# from django.contrib.staticfiles.templatetags.staticfiles import static
# 
# import requests
# Create your models here.

from CATH_API.lib import *
import urllib
from .domutil.util import *
# from utils_db import *


levels=[ None,
'root',
'Class',
'arch',
'topo',
'homsf',
's35',
's60',
's95',
's100'];

class blankobj(object):
    def __init__(self,**kwargs):
        for k,v in kwargs.iteritems():
            setattr(self,k,v)
        pass

# class text(models.Model):
#     content = models.TextField(blank = True, null = True)







from django_CATH.models import domain as domain_model

# class tabModel(models.Model):
#     def __init__(self,**kwargs):
#         models.Model.__
#     pass

class homsf_manager(models.Manager):
    def get_queryset(self):
        homsf_qset = super(homsf_manager, self).get_queryset().filter(level_id=5);
        homsf_qset = (homsf_qset.annotate(nDOPE_std=StdDev("classification__domain__nDOPE"))
              .annotate(nDOPE_avg=Avg("classification__domain__nDOPE"))
              .annotate(s35_count=Count("classification"))
              .annotate(s35_len_avg=Avg("classification__domain__domain_length"))
              # .annotate(superfamily="superfamily")
              )
        # for homsf_qset 
        return homsf_qset

class homsf_manager(models.Manager):
    def get_queryset(self):
        homsf_qset = super(homsf_manager, self).get_queryset().filter(level_id=5);
        homsf_qset = (homsf_qset.annotate(nDOPE_std=StdDev("classification__domain__nDOPE"))
              .annotate(nDOPE_avg=Avg("classification__domain__nDOPE"))
              .annotate(s35_count=Count("classification"))
              .annotate(s35_len_avg=Avg("classification__domain__domain_length"))
              # .annotate(superfamily="superfamily")
              )
        # for homsf_qset 
        return homsf_qset
linear = lambda d:  ' '.join( str(x) for x in sum([ [k,v] for k,v in d.iteritems()],[]))

class node_manager(models.Manager):

    def get_bytree(self, node_str, qnode = None):

        lst = [int(x) for x in node_str.split('.')]
        if lst[-1]:
            lst += [0]
        # if lst[:2] == [0,0]:
        ldep = len(lst)

        lst = [0,0]+lst;

        # idx = (x for x in lst)
        if not qnode:
            level = 2
            obj = super(node_manager, self);
            qset = obj.get_queryset()
            qset = qset.filter(level__id = level)
        else:
            # qset = 
            level = qnode.level.id + 1
            qset = qnode.classification_set
        while 1:
            # qdict = {'level__id':level,
                     # levels[level]: lst[level]}
            try:
                # qnode = qset.get(**qdict)
                qnode = qset.get(**{ levels[level]: lst[level]})
            except:
                resp = 0;
                # print('node %s not found'%(lst[1:level]))
                break

            if level == ldep:
                resp = 1
                break

            qset = qnode.classification_set
            level += 1

        # domain_set = super(node_manager, self).get();
        # domain_set.annotate(superfamily="")
        return (qnode,resp)

    # def get_superfamily(self):
    #     homsf_qset.manager = "homsf_manager"
class domain_manager(models.Manager):
    def get_queryset(self):
        domain_set = super(domain_manager, self).get_queryset();
        # domain_set.annotate(superfamily="")
        return domain_set
class defer_text_manager(models.Manager):
    def get_queryset(self,*args,**kwargs):
        qset = super(defer_text_manager, self).get_queryset(*args,**kwargs).defer('text');
        # domain_set.annotate(superfamily="")
        return qset

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    def to_values(self):
        return self


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class version(models.Model):
    name = models.CharField(default=None,max_length=10);
    def __str__(self):
        return self.name;
class level(models.Model):
    name = models.CharField(default=None,max_length=50)
    letter = models.CharField(default=None,max_length=1);
    def __str__(self):
        return self.name;


dft = 0
class classification(models.Model):    
    # homsf_ID = models.CharField(max_length=7, primary_key=True)
    # DFcols =

    Class = models.IntegerField(default=dft,null=True,db_index=True)
    arch = models.IntegerField(default=dft,null=True,db_index=True)
    topo = models.IntegerField(default=dft,null=True,db_index=True)
    homsf = models.IntegerField(default=dft,null=True,db_index=True)
    s35 = models.IntegerField(default=dft,null=True,db_index=True)
    s60 = models.IntegerField(default=dft,null=True)
    s95 = models.IntegerField(default=dft,null=True)
    s100 = models.IntegerField(default=dft,null=True)
    version =  models.ForeignKey(version, on_delete= models.CASCADE);
    level = models.ForeignKey(level,  on_delete=models.CASCADE)
    parent = models.ForeignKey("self", default=None,null=True, on_delete=models.CASCADE)
    
    def node_dict(self):
        return {
            'Class':self.Class,
            'arch':self.arch,
            'topo':self.topo,
            'homsf':self.homsf,
            's35':self.s35,
            's60':self.s60,
            's95':self.s95,
            's100':self.s100,
            # 'level_id':self.level_id,
            }
    def find_depth(self, depth):
        s = '';
        i = depth
        if not i:
            return('Not in any Class')
        for key in [self.Class,self.arch,self.topo,self.homsf,self.s35,self.s60,self.s95,self.s100]:
            i += -1
            s += str(key) + '.'
            if not i :
                return s.rstrip('.')
    def __str__(self):
        return self.find_depth(self.level.id)
    
    def superfamily(self):
        return self.find_depth(4)

    def superfamily_urled(self):
        sf = self.superfamily();
        url = reverse('domain_collection',args=[sf])
        htmldom = "<a href=\"{:s}\">{:s}</a>".format(url,sf)
        return htmldom
    
    def get_s35cnt(self):
        url = 'http://www.cathdb.info/version/v4_1_0/api/rest/superfamily/%s' % self.superfamily();
        cnt = fetch_cath(url)[1]["child_count_s35_code"]
        return cnt

    def child_count(self):
            return self.classification_set.count()


    # objects = models.Manager()
    objects = node_manager()
    homsf_objects = homsf_manager()
        # pass

    #     return("Superfamily %s"%self.homsf_ID())

class node_stat(models.Model):
    default_cols = [
    'node__superfamily_urled',
    'node__child_count',
    'Rsq_NBcount_Rcount',
    'Rsq_NBcount_Acount',
    'node__version__name',
                    # 's35_len_avg','nDOPE_avg','nDOPE_std',
                    ]

    node = models.OneToOneField(classification,
        on_delete= models.CASCADE,
        primary_key=True)
    Rsq_NBcount_Acount = models.FloatField(null = True);
    Rsq_NBcount_Rcount = models.FloatField(null = True);




class domain(models.Model):
    default_cols = [
            'domain_id_urled',
            'superfamily_urled',
            'view_chopped',
            'sf_s35cnt',
            'residue_count',
            'atom_count',
            # 'nDOPE',
            'nbpair_count',
            'domain_stat__maha_dist',
            'classification__version__name',]
    domain_id = models.CharField(max_length=7,db_index=True)
    domain_length = models.IntegerField(default=0,null=True)
    resolution = models.FloatField(default=0,null=True)
    nDOPE = models.FloatField(default=0,null=True)
    raw_DOPE = models.FloatField(default=0,null=True)
    # version =  models.ForeignKey(version, default=None,on_delete= models.CASCADE);
    # classification =  models.ForeignKey(classification, on_delete= models.CASCADE);
    classification =  models.OneToOneField(classification, on_delete= models.CASCADE);


    def __str__(self):
        return self.domain_id

    def superfamily(self):
        return(self.classification.superfamily())
    def superfamily_urled(self):
        return(self.classification.superfamily_urled())
    def view_chopped(self):        
        elem = '<a id="view3d" href="#view_{:s}" data-toggle="collapse"><img src="{:s}" alt="chopped_pdb"/></a>'.format( self.domain_id, static("imgs/rasmol.png"))
        return elem
    def domain_id_urled(self):
        version = 'current';
        url = "http://www.cathdb.info/version/{:s}/domain/{:s}/".format(version, self.domain_id)
        elem = '<a target="_blank" href="{:s}">{:s}</a>'.format(url, self.domain_id)
        return elem
    def residue_count(self):
        try: 
            c = self.domain_stat.res_count
        except Exception as e:
            c = None
            # print(e)
        return (c)
    def nbpair_count(self):
        try: 
            c = self.domain_stat.nbpair_count
        except Exception as e:
            c = None
            # print(e)
        return (c)
    def atom_count(self):
        try: 
            c = self.domain_stat.atom_count
        except Exception as e:
            c = None
            # print(e)
        return (c)
    
    # class_id = models.IntegerField(default=0)

templates/tst/3dviewer.html
<head>	

{% include "./style.html" %}


{% load static %}


 </head>



<body>

{# <div id="container-01" class="mol-container"></div> #}



<p>
<a href="#view_{{d.domain_id}}" data-toggle="collapse"><img src="/static/imgs/rasmol.png" alt="rasmol_pdb"></a>
  <button class="btn btn-primary" type="button" target="#collapseExample02" id="01" >
    Button with data-target
  </button>


</p>


<div class="collapse" id="view_{{d.domain_id}}" pdb-url="http://www.cathdb.info/version/current/api/rest/id/{{d.domain_id}}.pdb">
  <div class="card card-block" id="logs">
  You are viewing {{d.domain_id}}
	<div id="container" class="mol-container"></div>
  </div>
</div>




<p>Another paragraph!!!</p>

<div class="collapse" id="collapseExample02" ct="02" pdb-url="http://www.cathdb.info/version/current/api/rest/id/2c7wA00.pdb">
  <div class="card card-block" id="logs">
    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
	<div id="container" class="mol-container"></div>

  </div>
</div>

<table class="table table-bordered " id="myTable">
<thead>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>

<tbody>
    <tr data-toggle="collapse" data-target="#accordion" class="clickable-row">
        <td>Some Stuff</td>
        <td>Some more stuff</td>
        <td>And some more</td>
    </tr>


    {% with ''|center:100 as range %}
      {% for _ in range %}
        
        <tr class="clickable-row" id="row{{forloop.counter}}">
        <td colspan="3">
            {{ forloop.counter }}
            {# <div id="accordion" class="collapse" pdb-url="http://www.cathdb.info/version/current/api/rest/id/{{d.domain_id}}.pdb">     </div> #}
        </td>
        <td></td>
    </tr>
      {% endfor %}
    {% endwith %}
</tbody>
</table>
{# <script src="https://cdnjs.cloudflare.com/ajax/libs/jspanel3/3.9.3/jquery.jspanel.min.js"></script> #}
<script type="text/javascript">
    $('#01').click(function () {
        "use strict";
        var mypanel=$.jsPanel({
            position: {
                my: "left-top",
                at: "left-top",
                offsetY: 52
            },
            headerTitle: "ScatterPlot",
            content: "<p>A plot containing information about outlier</p>",

        });
            mypanel.content.append("<a href='#row1' onclick='$(`#row10`).click();' data-toggle='table'>row1</a>")

    });

$( document ).ready(function() {

   $('.table > tbody > tr').click(function() {
    $(this).addClass('bg-info').siblings().removeClass('bg-info');
  // row was clicked
    });
});
</script>

</body>
{# <div id="container-01" class="mol-container"></div> #}

templates/tst/PDBcollapse.html
<div class="collapse" id="view_{{d.domain_id}}" pdb-url="http://www.cathdb.info/version/current/api/rest/id/{{d.domain_id}}.pdb">
  {# <div class="card card-block" id="logs"> #}
  You are viewing {{d.domain_id}}
	<div id="container" class="mol-container"></div>
	{# <div id="container"></div> #}

  {# </div> #}
</div>

templates/tst/config.html
<div class="collapse" id="config" aria-expanded="true">

  <table class="table table-sm table-bordered">
{% load util_filter %}

  {% for f in field_names %}
  <tr></tr>
    <th>{{f}}:</th>
    <th>{{field_readable|getattribute_iter:f}}</th>
  <tr></tr>
  {% endfor %}
  </table>


  <section>



  <div class="card card-info card-inverse">
    <div class="card-block">
      <h4 class="card-title">Configuration</h4>
      <p class="card-text">
      </p><dl class="row">
        <dt class="col-sm-3">CLUSTERS_FILE</dt>
        <dd class="col-sm-9">/cath/homes2/ucbtnld/orengosvn/update/trunk/v4_2_0/clusters.json</dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">COMMIT</dt>
        <dd class="col-sm-9">NO (rollback)</dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">DB_HOST</dt>
        <dd class="col-sm-9">fletcher</dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">DB_NAME</dt>
        <dd class="col-sm-9">cathdb_current</dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">DB_PASS</dt>
        <dd class="col-sm-9">?????????????</dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">DB_USER</dt>
        <dd class="col-sm-9">nataliedawson</dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">MODE</dt>
        <dd class="col-sm-9">TEST</dd>
      </dl>
      <p></p>
    </div>
  </div>

  </section>

</div>

templates/tst/config_old.html
<div class="collapse" id="config" aria-expanded="true">

  <table class="table table-sm table-bordered">
{% load util_filter %}

  {% for f in field_names %}
  <tr></tr>
    <th>{{f}}:</th>
    <th>{{field_readable|getattribute_iter:f}}</th>
  <tr></tr>
  {% endfor %}
  </table>


  <section>




  </section>

</div>

templates/tst/index.html
<head>
	

{% include "./style.html" %}

{# {% include "./viewPDB.template" %} #}
{% include "./viewPDB.html" %}

{% load static %}

 </head>


<body>


<div class="container">
<section>

<div class="mt-1">
  <h3 class="display-3">
   Doped_CATH
  </h3>
</div>

<p class="lead">
	This page is generated from a list of CATH domain ID's, usually suspicious of being badly packed (high nDOPE).
  Each row represents a single domain from CATH.
  There is no button you can click, but clicking on shiny bluish text will lead you to domain page or superfamily page.
</p>

<p>
<button class="btn btn-info" type="button" data-toggle="collapse" data-target="#config" aria-expanded="true" aria-controls="config">
  Config
</button>
</p>

</section>


{% include "./config.html" %}


<!--     <ul>
        <li><a href="/tst/{{ q.id }}/">
        {{q.id}}||
        {{q.question_text }}||
        {{q.pub_date}}||
        {{q.choice_set.all}}</a></li>
    </ul> -->
{{tst_a}}

{% if query_set %}

<p class="table-heading">
Displaying {{query_set|length}} putative superfamily clusters for merging
</p>
	{{request}}
    <table class="table table-sm">
		<thead>
			<th>Domain id</th>
			<th>PDB</th>
			<th>Superfamily.ID</th>
			<th>Superfamily.S35_count</th>
			<th>Domain Length</th>
			<th>Raw DOPE</th>
			<th>Normalised DOPE</th>
		</thead>
		<tbody>
			
			

			{% for d in query_set %}
			<tr>
				<th><a target="_blank" href="http://www.cathdb.info/version/current/domain/{{d.domain_id}}/">{{d.domain_id}}</a></th>
				<th>
				{# <a target="_blank" href="http://www.cathdb.info/version/current/api/rest/id/{{d.domain_id}}.pdb"><img src="{% static "imgs/rasmol.png" %}" alt="rasmol_pdb"/></a></th> #}
				<a href="#view_{{d.domain_id}}" data-toggle="collapse"><img src="{% static "imgs/rasmol.png" %}" alt="rasmol_pdb"/></a></th>

				{# <th><a href="/tst/domain/{{ d.domain_id }}/">{{d.domain_id}}</a></th> #}
				<th>
				<a target="_blank" href="/tst/superfamily/{{d.superfamily}}/">
				{{d.superfamily}}</a> </th>
				{# {{d.superfamily}}				</th> #}
				{# <th>{{d.classification.get_s35cnt}}</th> #}
				<th>{{d.sf_s35cnt}}</th>
				<th>{{d.domain_length}}</th>
				<th>{{d.raw_DOPE}}</th>
				{# <th>{{d.classification}}</th> #}
				<th>{{d.nDOPE}}</th>
			</tr>

			<tr>
        		<td colspan="10">
            		{# <div id="view_{{d.domain_id}}" class="collapse" pdb-url="http://www.cathdb.info/version/current/api/rest/id/{{d.domain_id}}.pdb"> #}
            		{# halsdfhlsadf #}
            		{# sadfjksadlfjl #}
						{# <div id="container" class="mol-container"></div> #}
            		{# </div> #}
					{% include "./PDBcollapse.html" %}

        		</td>
		    </tr>
			{# {% include "./PDBcollapse.temp" %} #}
		
			{% endfor %}
			{# {% for valst in query_set.values_list %} #}
	<!--		<tr>
				<th>{{valst.0}}</th>
				<th>{{valst.1}}</th>
				<th>{{valst.2}}</th>
				<th>{{valst.3}}</th>
				<th>{{valst.4}}</th>

			</tr>
			{# {% endfor %} #}
	-->
		</tbody>
	</table>
{% else %}
    <p>No domain list is provided.</p>
{% endif %}


</div>



</body>

templates/tst/style.html
{# <script src="/static/js/3Dmol-min.js" crossorigin="anonymous"></script> #}

<script src="/static/js/jquery-3.2.1.min.js" crossorigin="anonymous"></script>
<!-- <script src="/static/js/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script> -->
{# <script src="/static/js/jquery-3.2.1.slim.js"  crossorigin="anonymous"></script>  #}

<script src="/static/js/jquery.jspanel-compiled.js"  crossorigin="anonymous"></script> 

{# <script src="/static/js/pv.min.js" crossorigin="anonymous"></script> #}

    
<script src="/static/js/tether.min.js"
 crossorigin="anonymous"></script>
    
{# <script src="/static/js/bootstrap.min.js"></script> #}
<script src="bootstrap.min.js"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>


<script src="/static/js/d3.v4.min.js"></script>



<link rel="stylesheet" href="/static/js/jquery.jspanel.css"  crossorigin="anonymous">

<link rel="stylesheet" href="/static/js/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

<link rel="stylesheet" href="/static/js/font-awesome.min.css">






<!--   <link rel="stylesheet" href="/style.css">
  <script src="/merge_tree.js"></script>
 -->
<script type="text/javascript">
function addslashes(string) {
    return string.replace(/\\/g, '\\\\').
        replace(/\u0008/g, '\\b').
        replace(/\t/g, '\\t').
        replace(/\n/g, '\\n').
        replace(/\f/g, '\\f').
        replace(/\r/g, '\\r').
        replace(/'/g, '\\\'').
        replace(/"/g, '\\"');
};
</script>

<style type="text/css">
    
.not_bold{
    font-weight:normal
}​

</style>


<script type="text/javascript">
var clipboard = Clipboard('.copy');
// var clipboard = new Clipboard(btns);
clipboard.on('success', function(e) {
    console.log(e);
});
clipboard.on('error', function(e) {
    console.log(e);
});
console.log(clipboard)
    // new Clipboard('.btn');

//   function highlight(j_alias){
//   $(j_alias).addClass('bg-info').siblings().removeClass('bg-info');
//   // $('body').
//   // $(j_alias).get(0).scrollIntoView();
//   // scrollTo(j_alias)
//   // $(j_alias).get(0).click();
// }
// $( document ).ready(function() {

//   $('.clickable-row').click(function() {
//       // $(this).addClass('highlight').siblings().removeClass('highlight');
//       // $(this).addClass('active').siblings().removeClass('active');

//       // $(this).addClass('bg-info').siblings().removeClass('bg-info');
//       highlight(this);
//       // $(j_alias).addClass('bg-info').siblings().removeClass('bg-info');

//       // $(this).find("#view3d").attr("href").eval();
//       // $(this).find("#view3d").trigger()
//       var elem = $(this).find("#view3d");
//       elem = elem.get(0);
//       elem.click();
//       console.dir(elem);
//       });

// });
// $(function () {
//   $('[data-toggle="popover"]').popover()
// })

</script>


{# Loading customised filer #}
{% load util_filter %}

templates/tst/table_head.html
{% load util_filter %}

		<thead>

        {% for f in field_names %}
          <th>
            {% with fshort=meta.field_short|getattribute_none:f %}
              {% if  fshort == "None" %}
              {{ f }}
              {% else %}
              {{fshort}}
              {% endif %}
            {% endwith %}
          </th>
        {% endfor %}      
		</thead>

templates/tst/table_legend.html
<div class="collapse" id="config" aria-expanded="true">


<div class="mt-1">
  <h4 class="display-5">
  Table Legend Table
  </h4>
</div>

  <table class="table table-bordered">

{% load util_filter %}




<!-- 
Print the Legend table
-->

  <tr>
    <th>Table Key</th>
    <th colspan="3">
    Readable
    </th>
  </tr>

  {% for f in field_names %}
  <tr>
    <th>

      {% with fshort=meta.field_short|getattribute_none:f %}

        {% if  fshort == "None" %}
        {{f}}
        {% else %}
        {{fshort}}
        {% endif %}

      {% endwith %}


    </th>
    <th colspan="3">
      <span class="not_bold">
      {{meta.field_readable|getattribute_none:f}}
      </span>
    </th>
  </tr>
  {% endfor %}



  </table>


</div>

templates/tst/table_row_attr.html
{% load util_filter %}	
  			<tr id="dbid_{{d.id}}" class="clickable-row">
					{% for f in field_names %}
					<th> 
          {% with col=d|getattribute_iter:f  %}
  
            {% if col|get_type  == 'float' or col|get_type  == 'long' %}
                {{ col|floatformat:3}}
            {% else %}
                {{col}}                {# Oh no! #}
            {% endif %}

          {% endwith %}
          </th>

					{% endfor %}
				</tr>